"""empty message

Revision ID: a2b0f8caceb9
Revises: 
Create Date: 2021-05-27 18:52:55.568067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2b0f8caceb9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('file_type', sa.String(length=10), nullable=False),
    sa.Column('location', sa.String(length=36), nullable=False),
    sa.Column('storage_file_name', sa.String(length=100), nullable=False),
    sa.Column('uploaded_file_name', sa.String(length=100), nullable=False),
    sa.Column('upload_time', sa.DateTime(), nullable=True),
    sa.Column('upload_by', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('issuer', sa.String(length=200), nullable=True),
    sa.Column('subject', sa.String(length=200), nullable=True),
    sa.Column('ref_no', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('last_update_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ref_no')
    )
    op.create_table('issuers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('user_role', sa.String(length=10), nullable=False),
    sa.Column('login_id', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('login_id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('issuers')
    op.drop_table('documents')
    op.drop_table('attachments')
    # ### end Alembic commands ###
